plugins {
    id("com.somnus.bom")
}

dependencies {
    api(platform(org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES))
    api(platform("org.springframework.cloud:spring-cloud-dependencies:${libs.versions.springCloud.get()}"))
    api(platform("com.alibaba.cloud:spring-cloud-alibaba-dependencies:${libs.versions.springCloudAlibaba.get()}"))
    api(platform("com.squareup.okhttp3:okhttp-bom:${libs.versions.okhttp3.get()}"))
    constraints {
        api("com.playtika.reactivefeign:feign-reactor-cloud:${libs.versions.reactivefeign.get()}")
        api("com.playtika.reactivefeign:feign-reactor-webclient:${libs.versions.reactivefeign.get()}")
        api("com.playtika.reactivefeign:feign-reactor-spring-configuration:${libs.versions.reactivefeign.get()}")
        api("io.jsonwebtoken:jjwt-jackson:${libs.versions.jjwt.get()}")
        api("io.jsonwebtoken:jjwt-impl:${libs.versions.jjwt.get()}")
        api("com.nimbusds:nimbus-jose-jwt:${libs.versions.nimbusJose.get()}")
        api("org.springframework.security:spring-security-oauth2-authorization-server:${libs.versions.oauth2AuthorizationServer.get()}")
        api("com.baomidou:mybatis-plus-boot-starter:${libs.versions.mybatisPlus.get()}")
        api("com.github.pagehelper:pagehelper-spring-boot-starter:${libs.versions.pagehelper.get()}")
        api("org.redisson:redisson:${libs.versions.redisson.get()}")
        api("org.springdoc:springdoc-openapi-webflux-ui:${libs.versions.springdoc.get()}")
        api("org.apache.shardingsphere:sharding-jdbc-spring-boot-starter:${libs.versions.shardingsphere.get()}")
        api("com.alibaba:easyexcel:${libs.versions.alibabaEasyexcel.get()}")
        api("com.google.guava:guava:${libs.versions.googleGuava.get()}")
        api("org.modelmapper:modelmapper:${libs.versions.modelmapper.get()}")
        api("eu.bitwalker:UserAgentUtils:${libs.versions.userAgent.get()}")
        api("com.netease.cloud:nos-sdk-java-publiccloud:${libs.versions.neteaseCloud.get()}")
        api("com.aliyun.oss:aliyun-sdk-oss:${libs.versions.aliyunOss.get()}")
        api("com.github.binarywang:weixin-java-mp:${libs.versions.wechat.get()}")
        api("net.logstash.logback:logstash-logback-encoder:${libs.versions.logstashLogback.get()}")
        api("com.github.danielwegener:logback-kafka-appender:${libs.versions.logbackKafka.get()}")
        api("org.apache.shardingsphere.elasticjob:elasticjob-lite-spring-boot-starter:${libs.versions.elasticjob.get()}")
        api("com.xuxueli:xxl-job-core:${libs.versions.xxlJob.get()}")
        api("javax.persistence:javax.persistence-api:${libs.versions.persistenceApi.get()}")
        api("org.ow2.asm:asm:${libs.versions.ow2Asm.get()}")
        api("cn.hutool:hutool-all:${libs.versions.hutool.get()}")
        api("org.apache.commons:commons-text:${libs.versions.commonsText.get()}")
        api("commons-io:commons-io:${libs.versions.commonsIo.get()}")
        api("org.lionsoul:ip2region:${libs.versions.ip2region.get()}")
        api("org.apache.curator:curator-recipes:${libs.versions.curatorRecipes.get()}")
    }
}
